### ISSUE TITLE
NAIP /offcial_train.py

### ISSUE THREAD

**Issue by ZhenboZhao77** [ssocean/NAIP#4]
165  174
这两行都定义了batch_size会有冲突吗？还是有不一样？

**Comment by ZhenboZhao77** [comment]
你好作者！我发现两个是冲突的，删除任意一个都可run

**Comment by ZhenboZhao77** [comment]
还有一个 作者， inference.py这个文件好像我也没有发现。抱歉

**Comment by ssocean** [comment]
> 你好作者！我发现两个是冲突的，删除任意一个都可run

哦哦 确实  我们对代码做了一些排版上的优化 可能在后期调整的时候 哪里复制错了

**Comment by ssocean** [comment]
> 还有一个 作者， inference.py这个文件好像我也没有发现。抱歉！
这个现在已经更名为了demo.py了，我稍后会对您说的这两个问题做出修正~感谢

**Comment by ZhenboZhao77** [comment]
okok,感谢回复。优秀流畅的代码

**Comment by ssocean** [comment]
> okok,感谢回复。优秀流畅的代码

hhhh 感谢关注~
